apiVersion: compute.gcp.upbound.io/v1beta1
kind: SharedVPCHostProject
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/sharedvpchostproject
  labels:
    testing.upbound.io/example-name: host
  name: host
spec:
  forProvider:
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

